### ISSUE TITLE
penny encounters thad

### ISSUE THREAD

**Issue by babyshoes** [NQNStudios/SpaceStories#11]
while being dragged away, if she is to be returned to planet X

**Comment by NQNStudios** [comment]
With the way I've written the hyperfuel mushroom trip, this should happen in the first act, from the engineers' perspective, in the section `princess_encounter` and if Thad appears sympathetic enough post-torture and lets slip that Starson II is to blame, he just might get the girl in the end.

**Comment by NQNStudios** [comment]
Keep in mind we need 2 versions of this scene--- one from engi perspective, and one from Penny's perspective. I'll make a separate issue to hopefully eliminate confusion

**Comment by NQNStudios** [comment]
this issue is for thad to choose what he says when they meet during the first pass. later the scene will replay cfrom penny's perspective so we can see what she thinks.
