### ISSUE TITLE
secret evacuation

### ISSUE THREAD

**Issue by babyshoes** [NQNStudios/SpaceStories#16]

**Comment by NQNStudios** [comment]
This can fulfill the second choice for penny to bump into Thad that @babyshoes mentioned [here](https://github.com/NQNStudios/SpaceStories/commit/a5924c631a44bfdfe0c621c0385d77cb8950edf2#diff-4b57e5aaac85526dc36e799269638d15R417).

That will then dovetail into the #18 ending (after the captain's third act plays out).

**Comment by babyshoes** [comment]
folded this in w/ saving thad ending #18 in 5c17222
