### ISSUE TITLE
ousting of bomb

### ISSUE THREAD

**Issue by babyshoes** [NQNStudios/SpaceStories#17]

**Comment by NQNStudios** [comment]
This scene presumably takes place in the `deactivate_bomb` knot. It needs to be a dramatic reveal of whatever the crucial Fatal Flaw is that the rhizoXls discovered in the Denuded Battle. What's the funniest place they could put a bomb where it would fully destroy/disable a person?

**Comment by NQNStudios** [comment]
Maybe the goal was to blow up the thrusters so the ship would just float through space "impotent" and the crew slowly suffocate

**Comment by NQNStudios** [comment]
And, if that's the case, #22 will have to play with the aftermath of that.

**Comment by babyshoes** [comment]
831811d
