### ISSUE TITLE
thad love

### ISSUE THREAD

**Issue by babyshoes** [NQNStudios/SpaceStories#18]

**Comment by NQNStudios** [comment]
This will happen in 2 scenarios:
1) Penny deactivates the bomb but Starson II is outraged that she knew all along (she fails to smooth it over).
2) Penny leaves Starson II to die, but saves Thad.

Now that #39 (Thad is asexual) this ending will have to look a lot different. Maybe their romance fails if Starson II is out of the picture.

**Comment by babyshoes** [comment]
5c17222 is written to this, but again i think there's more room for interesting possibilities
