### ISSUE TITLE
thruple love

### ISSUE THREAD

**Issue by babyshoes** [NQNStudios/SpaceStories#20]

**Comment by NQNStudios** [comment]
Penny narrates how she's learned the two humans complement each other and without both she couldn't be satisfied. Starson satisfies her carnal, submissive desires while Thad is a soul companion who she loves to engulf (dominate) lolllll

**Comment by babyshoes** [comment]
wrote c013f7e in response to this, but i'm not entirely happy making thad purely submissive. could be more nuanced probably
