### ISSUE TITLE
attempt to evade punishment

### ISSUE THREAD

**Issue by babyshoes** [NQNStudios/SpaceStories#24]
--> may or may not result in princess encounter?

**Comment by NQNStudios** [comment]
The way I've written the mutiny branch, this scene won't be necessary. Pending implementation of the spiketheair branch, we might be able to cut this.

**Comment by NQNStudios** [comment]
Indeed it looks like this is the case. I've written it so that in the spike_the_air branch, the engineers don't get caught at all
