### ISSUE TITLE
memory of courtship

### ISSUE THREAD

**Issue by babyshoes** [NQNStudios/SpaceStories#4]
catfishing? never been attracted to a female before??

**Comment by NQNStudios** [comment]
Penny wonders why Starson is so turned on by her "philanges"

**Comment by NQNStudios** [comment]
Her first impression from their compusor facecalls was that he had an air of strange superiority, which at first she found funny. But with time, almost without realizing it, she found that every word he spoke implanted a seed of doubt, that he might legitimately be the chosen, superior, alpha, etc. and this was a mythos that was frighteningly easy to get caught up in.
