### ISSUE TITLE
uninterrupted "love" scene

### ISSUE THREAD

**Issue by babyshoes** [NQNStudios/SpaceStories#9]
[only happens if starson does not need to go deal w/ troublemakers]

penny is intrigued more than anything else. "he was inexplicably fixated on my phalanges"

**Comment by NQNStudios** [comment]
Penny notes that Starson seems to be expressing his ego through a form of simulated domination (she could kill him instantly) and he shouts "who's your daddy" which she kinda likes because she has no idea what daddy means
